[project]
name = "ai-resume-critiquer"
version = "0.1.0"
description = "AI-powered resume critique tool"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "streamlit>=1.45.1",
    "PyPDF2>=3.0.1",
    "google-generativeai>=0.3.0",
    "python-dotenv>=1.1.0",
]
